[package]
name = "duration-str"
version = "0.3.5"
authors = ["baoyachi <liaoymxsdl@gmail.com>"]
edition = "2018"
description = "duration string parser"
keywords = ["duration", "time", "duration-string", "duration-parser", "time-parser"]
readme = "README.md"
categories = ["parsing", "date-and-time"]
repository = "https://github.com/baoyachi/duration-str"
license = "MIT AND Apache-2.0"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.1.2"
anyhow = "1.0.38"
chrono = { version = "0.4.19", optional = true }
serde = { version = "1.0.124", features = ["derive"], optional = true }
serde_json = { version = "1.0.64", optional = true }
rust_decimal = { version = "1.15", default-features = false }

[features]
default = ["chrono", "serde", "serde_json"]
